# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [1]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

Use the next code cell to fetch the dataset.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [3]:
# List all the tables in the "hacker_news" dataset
tables = list(client.list_tables(dataset))
print('Ntables = ', len(tables))

Ntables =  1

In [10]:
# Print names of all tables in the dataset (there is only one)
for table in tables:  
    print(table.table_id)

crime

In [4]:
num_tables = len(tables)  # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [ ]:
#q_1.hint()
#q_1.solution()

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [17]:
# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

In [31]:
# Obtain the total number of columns
ncols = len(table.schema)

print('Ncols = ', ncols)

# Obtain the number of columns with TIMESTAMP data-type
ncols_TIMESTAMP = 0
for column in table.schema:
    dtype = column.field_type
    if dtype == 'TIMESTAMP':
        ncols_TIMESTAMP += 1

print('Ncols (TIMESTAMP) = ', ncols_TIMESTAMP)

Ncols =  22
Ncols (TIMESTAMP) =  2

In [32]:
num_timestamp_fields = ncols_TIMESTAMP # Put your answer here

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [ ]:
#q_2.hint()
#q_2.solution()

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [33]:
table.schema

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', None, (), None),
 SchemaField('case_number', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('block', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('iucr', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('primary_type', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('location_description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('arrest', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('domestic', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('beat', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('district', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('ward', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('community_area', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('fbi_code', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('year', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('location', 'STRING', 'NULLABLE', None, (), None)]

In [36]:
fields_for_plotting = ['latitude', 'longitude'] # Put your answers here

# Check your answer
q_3.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [ ]:
#q_3.hint()
#q_3.solution()

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [42]:
df = client.list_rows(table, max_results = 5).to_dataframe()

# Take only some of the columns
filtered_df = df[['latitude', 'longitude', 'location', 'x_coordinate', 'y_coordinate']]

filtered_df

,latitude,longitude,location,x_coordinate,y_coordinate
0,41.883375,-87.629428,"(41.883375237, -87.629427772)",1175930.0,1900878.0
1,41.885482,-87.627936,"(41.885481891, -87.627935689)",1176330.0,1901649.0
2,41.886832,-87.627557,"(41.886832476, -87.627557257)",1176429.0,1902142.0
3,41.887148,-87.627994,"(41.887148006, -87.627994483)",1176309.0,1902256.0
4,41.884650,-87.627915,"(41.884650262, -87.627915459)",1176338.0,1901346.0